name: Build account-app
on:
  push:
    paths:
      - "apps/account-app/**"
      - "libs/greeter/**"
      - "libs/profile/**"
      - "*.gradle.kts"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Run gradle build
        run: ./gradlew :apps:account-app:build

      - uses: actions/upload-artifact@v2
        with:
          path: apps/account-app/build/libs/*.jar